config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :users
  end
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, :content, presence: true
  validates :deadline, :status, :priority, presence:true
  
  scope :name_like, -> (name) {where('(name LIKE ?)',"%#{name}%")}
  scope :status_is, -> (status) { where(status: status) }

  enum status:{ 未着手: 0, 着手中: 1, 完了: 2 }
  enum priority:{ 低: 0, 中: 1, 高: 2 }

  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :tasks, dependent: :destroy
  
  before_update :admin_change_check
  before_destroy :admin_change_check
  def admin_change_check
    target = User.find_by(id: self.id)
    if User.where(admin: true).count <= 2
      if target.admin
        throw :abort
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :admin_user

  def index
    @users = User.all.includes(:tasks)
    
    @users = @users.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザーを登録しました"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "ユーザーを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました"
    else
      redirect_to admin_users_path, notice: "管理者は2人以上必要です"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def admin_user
    redirect_to root_path , notice: "管理者以外はアクセスできません" unless current_user.admin?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    # 現在ログイン中のユーザが存在しない場合、ログインページにリダイレクトさせる。
    if @current_user == nil
      redirect_to new_session_path, notice: "ログインが必要です"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
# binding.pry
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [ :new, :edit, :show]
  before_action :authenticate_user, only: [:new, :edit, :update, :destroy]

  def index
      # @tasks = current_user.tasks
      @tasks = Task.all.order(created_at: :desc)
    
    if params[:sort_expired]
      # @tasks = Task.all.order(deadline: :desc)
      @tasks = current_user.tasks.order(deadline: :desc)
    else
      @tasks = Task.all.order(created_at: :desc)
      #  @tasks = current_user.tasks.order(created_at: :desc)
    end  

    if params[:sort_priority]
      @tasks = Task.all.order(priority: :desc)
    end  

    if params[:name].present? && params[:status].present?
      @tasks = Task.where('name LIKE ?', "%#{params[:name]}%")
      @tasks = @tasks.where(status: params[:status])
    elsif params[:name].present?
          @tasks = Task.where('name LIKE ?', "%#{params[:name]}%")
      
    elsif params[:status].present?
          @tasks = Task.where(status: params[:status])
    end
    
      @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?

      @tasks = @tasks.page(params[:page]).per(20)
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.new(task_params)
    
    if @task.save
      redirect_to tasks_path, notice: "タスクを作成しました！"
    else
      render :new
    end
  end

  def Show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました"
  end

  private
  def task_params
    params.require(:task).permit(:name, :content, :deadline, :status, :priority, { label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:index, :new, :show]
  before_action :ensure_correct_user, only: [:show, :edit, :update]

  def new
    if logged_in?
      redirect_to tasks_path, notice: "新規ユーザー作成は、一度ログアウトしてください"
    else
    @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザーを編集しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password,
                                 :password_confirmation)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to tasks_path, notice: "権限がありません"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>ユーザー編集画面</h2><hr>
<div class="w-50">
  <%= form_with(model: @user, local: true, url: admin_user_path) do |form| %>
    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name,  placeholder: "ユーザー名を入力..", class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email %>
      <%= form.text_field :email, placeholder: "メールアドレスを入力..", class: "form-control" %>
    </div>
    <div class="w-25 mb-3">
      <%= form.label :admin %>
      <%= form.select :admin,[['付与しない',false],['付与する',true]], { include_blank: '選択してください' }, class: "form-control" %> 
    </div>
    <%= form.label :password %>
    <%= form.hidden_field :password, value: @user.password_digest %><br>
    <%= form.label :password_confirmation %>
    <%= form.hidden_field :password_confirmation, value: @user.password_digest %><br>
    <br>
    <br>
      <%= form.submit '編集する', class: "btn btn-success" %>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<h1>ユーザー管理画面</h1><hr>
<%= link_to 'ユーザー登録', new_admin_user_path, class: "btn btn-info" %> <br><br>
<table class="table">
  <thead>
    <tr>
      <th>ユーザーid</th>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
      <th>ユーザー登録日</th>
      <th>タスク登録数</th>
      <th>管理者</th>
      <th>　</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.strftime('%Y-%m-%d') %></td>
      <td><%= user.tasks.count %>件</td>
      <td><%= user.admin %></td>
      <td>　</td>
      <td><%= link_to '詳細', admin_user_path(user.id), class: "btn btn-outline-primary" %></td>
      <td><%= link_to '編集', edit_admin_user_path(user.id), class: "btn btn-outline-success"  %></td>
      <td><%= link_to '削除', admin_user_path(user.id), method: :delete,
          data: { confirm: '本当に削除していいですか？' }, class: "btn btn-outline-danger", id: "confirm_delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagenate"><%= paginate @users %></div>

app/views/admin/users/new.html.erb
<h2>ユーザー新規登録画面</h2><hr>
<div class="w-50">
  <%= form_with(model: @user,url: admin_users_path, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name,  placeholder: "ユーザー名を入力..", class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email %>
      <%= form.text_field :email, placeholder: "メールアドレスを入力..", class: "form-control" %>
    </div>
    <div class="w-25 mb-3">
    <%= form.label :admin %>
    <%= form.select :admin,[['付与しない',false],['付与する',true]], { include_blank: '選択してください' }, class: "form-control" %> 
    </div>
    <div class="w-50 mb-3">
      <%= form.label :password %>
      <%= form.text_field :password, class: "form-control" %>
    </div>
    <div class="w-50 mb-3">
      <%= form.label :password_confirmation %>
      <%= form.text_field :password_confirmation ,class: "form-control" %>
    </div>
   
    <br>
      <%= form.submit '登録する', class: "btn btn-primary" %>
  <% end %>
</div>

<h1>Admin::Users#new</h1>
<p>Find me in app/views/admin/users/new.html.erb</p>

app/views/admin/users/show.html.erb
<h2>ユーザー情報</h2>

<table class="table table-striped w-50">
  <tbody>
      <tr>
        <th>ユーザー名</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>アカウント登録日</th>
        <td><%= @user.created_at.strftime('%Y-%m-%d %T') %></td>
      </tr>
      <tr>
        <th>管理者権限</th>
        <td><%= @user.admin %></td>
      </tr>
  </tbody>
</table><hr>
<h3>「<%= @user.name %>」のタスク一覧</h3>
  <table class="table">
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>登録日時</th>
      <th>ステータス</th>
      <th>優先度</th>
    </tr>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.content %></td>
      <td><%= task.deadline %>　　</td>
      <td><%= task.created_at.strftime('%Y-%m-%d %T') %></td>
      <td><%= task.status %>　　</td>
      <td><%= task.priority %>　　</td>
    </tr>
    <% end %>
  </tbody>
</table><hr>
<%= link_to "管理一覧画面へ", admin_users_path, class:'btn btn-info' %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href=""></a>
    <p>Copyright ©2020 task management</p>
  </div>
  <br><br><br><br><br>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="">Task Management</a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarForm" aria-controls="navbarForm" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="login">
    <% if logged_in? %>
        <%= link_to "Myページ(ログイン中)", user_path(current_user.id), class: "btn btn-info btn-sm" %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: "btn btn-secondary btn-sm" %>
    <% else %>
        <%= link_to "Sign up", new_user_path, class: "btn btn-primary btn-sm" %>
        <%= link_to "Login", new_session_path, class: "btn btn-secondary btn-sm" %>
    <% end %>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryleafTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="alert alert-warning alert-dismissible fade show" >
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </div>
    
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>タスク編集画面</h2><hr>
<div class="w-50">
  <%= form_with(model: @task, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :content %>
      <%= form.text_area :content, class: "form-control" %>
    </div>
    <div class="w-50 mb-3">
      <%= form.label :deadline %>
      <%= form.date_field :deadline, class: "form-control" %>
    </div>
    <div class="w-50 mb-3">
      <%= form.label :status %>
      <%= form.select :status, Task.statuses.keys.to_a, { include_blank: '選択してください'}, class: "form-control" %>
    </div>
    <div class="w-50 mb-3">
      <%= form.label :priority %>
      <%= form.select :priority, Task.priorities.keys.to_a, { include_blank: '選択してください'}, class: "form-control" %>
    </div>
    <div class="field">
    <%= form.label :label %><br>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
    </div>
    <br>
    <%= form.submit '更新する', class:"btn btn-success" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= form_with url: tasks_path, method: :get, local: true do |f| %>
  <div class="row w-75">
      <div class="col">
        <span>タスク名</span>
        <%= f.text_field :name, placeholder: "検索..", class: "form-control" %>
      </div>
      <div class="col">
      <span>ステータス</span>
        <%= f.select :status, Task.statuses.keys.to_a, { include_blank: '選択してください'}, class: "form-control" %>
      </div>
      <div class="col">
      <span>ラベル</span>
      <%= f.select("label_id", Label.pluck(:name, :id), { include_blank: '選択してください' }, class: "form-control") %>
      </div>
      <%= f.submit '検索', class: "btn btn-outline-info" %>
  </div>
<% end %><hr>
  <%= link_to '新規登録', new_task_path, class: "btn btn-primary" %><br><br><span>　<span>
  <%= link_to "終了期限でソートする", tasks_path(sort_expired: "true"),class: "btn btn-secondary btn-sm" %><span>　<span>
  <%= link_to "優先度高い順でソート", tasks_path(sort_priority: "true"),class: "btn btn-secondary btn-sm" %><br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>登録日時</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th>ラベル</th>
      <th>ユーザー名</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.created_at.strftime('%Y-%m-%d %T') %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td>
        <% task.labels.each do |label| %>
          <p class="badge badge-warning"><%= label.name %></p>
        <% end %>
      </td>
        <td><%= task.user.name %></td>
        <td><%= link_to '詳細', task_path(task.id), class: "btn btn-outline-primary" %></td>
        <% if logged_in? %>
        <td><%= link_to '編集', edit_task_path(task.id), class: "btn btn-outline-success" %></td>
        <td><%= link_to '削除', task_path(task.id), method: :delete, class: "btn btn-outline-danger" , data: {confirm: "本当に削除していいですか？"} %></td>
        <% else %>
        <td>　</td>
        <td>　</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table><br>
<div class="pagenate"><%= paginate @tasks %></div>

app/views/tasks/new.html.erb
<h2>タスク新規登録画面</h2><hr>
<% if @task.errors.any? %>
    <div style="color:red;">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<div class="w-50">
  <%= form_with(model: @task, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name,  placeholder: "タスク名を入力..", class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :content %>
      <%= form.text_area :content, placeholder: "タスクの詳細を入力してください..", class: "form-control" %>
    </div>
    <div class="w-50 mb-3">
      <%= form.label :deadline %>
      <%= form.date_field :deadline, class: "form-control" %>
    </div>
    <div class="w-50 mb-3">
      <%= form.label :status %>
      <%= form.select :status, Task.statuses.keys.to_a, { include_blank: '選択してください'} ,class: "form-control" %>
    </div>
    <div class="w-50 mb-3">
      <%= form.label :priority %>
      <%= form.select :priority, Task.priorities.keys.to_a, { include_blank: '選択してください'} ,class: "form-control" %>
    </div>
    <div class="field">
    <%= form.label :label %><br>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
    </div>

    <br>
      <%= form.submit '登録する', class: "btn btn-primary" %>
  <% end %>
</div><hr>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1><br>

<table class="table table-striped w-50">
  <tbody>
      <tr>
        <th><%= t('activerecord.attributes.task.name') %></th>
        <td><%= @task.name %></td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.task.content') %></th>
        <td><%= @task.content %></td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.task.deadline') %></th>
        <td><%= @task.deadline %>　　</td>
      </tr>
      <tr> 
        <th><%= t('activerecord.attributes.task.created_at') %></th>
        <td><%= @task.created_at.strftime('%Y-%m-%d %T') %></td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.task.status') %></th>
        <td><%= @task.status %>　　</td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.task.priority') %></th>
        <td><%= @task.priority %>　　</td>
      </tr>
      <tr>
        <th><%= t('activerecord.attributes.task.label') %></th>
        <td> <% @task.labels.each do |label| %>
          <p class="badge badge-warning"><%= label.name %></p>
        <% end %>
        </td>
      </tr>
  </tbody>
</table><hr>
<%= link_to "タスク一覧に戻る", tasks_path, class: "btn btn-outline-primary" %>

app/views/users/edit.html.erb
<h2>ユーザー編集画面</h2><hr>
<div class="w-50">
  <%= form_with(model: @user, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <div class="w-25 mb-3">
      <%= form.label :admin %>
      <%= form.select :admin,[['付与しない',false],['付与する',true]], { include_blank: '選択してください' }, class: "form-control" %> 
    </div>
    <%= form.label :password %>
    <%= form.hidden_field :password, value: @user.password_digest %><br>
    <%= form.label :password_confirmation %>
    <%= form.hidden_field :password_confirmation, value: @user.password_digest %><br>
    <br>
      <%= form.submit '編集する', class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1><hr>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="w-50">
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "名前を入力..", class:"form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, placeholder: "メールアドレスを入力..", class:"form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "パスワードを入力..", class:"form-control" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "確認用パスワードを入力..", class:"form-control" %><br>
  <%= f.submit "アカウント作成",class: "btn btn-success" %>
<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1><hr>

<p>ユーザー情報</p>
<table class="table table-striped w-50">
  <tbody>
      <tr>
        <th>ユーザー名</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>アカウント登録日</th>
        <td><%= @user.created_at.strftime('%Y-%m-%d %T') %></td>
      </tr>
      <tr>
      <th>管理者権限</th>
      <td><%= @user.admin %></td>
    </tr>
  </tbody>
</table>
<%= link_to '編集', edit_user_path(@user.id), class: "btn btn-outline-success" %><br><hr>
<%= link_to 'ユーザー管理画面へ', admin_users_path %><br><hr>
<h3>Myタスク一覧</h3>
  <table class="table">
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>登録日時</th>
      <th>ステータス</th>
      <th>優先度</th>
    </tr>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.content %></td>
      <td><%= task.deadline %>　　</td>
      <td><%= task.created_at.strftime('%Y-%m-%d %T') %></td>
      <td><%= task.status %>　　</td>
      <td><%= task.priority %>　　</td>
    </tr>
    <% end %>
  </tbody>
</table><hr>
<%= link_to "投稿一覧へ", tasks_path, class:'btn btn-info' %>